### ISSUE TITLE
Kolmogorov equations through neural nets

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/NeuralNetDiffEq.jl#22]
https://arxiv.org/pdf/1806.00421.pdf

**Comment by ChrisRackauckas** [comment]
https://github.com/juliusberner/Deep-Multilevel-Kolmogorov-PDE-Solver

**Comment by ashutosh-b-b** [comment]
I have started working on this.

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/NeuralNetDiffEq.jl/pull/61 is it. Remaining details:

- Instead of a `KolmogorovPDEProblem`, it should just use `SDEProblem` with distribution input.
- Needs documentation
- Needs the ability to do high-dimensional SDEs
- Needs a high dimensional SDE test
- Use the ensemble interface https://docs.juliadiffeq.org/latest/features/ensemble/ for the ensemble of solutions to parallelize it.

I think if you take this all the way, a nice paper can be written on it.

**Comment by ChrisRackauckas** [comment]
Completed by @ashutosh-b-b
