### ISSUE TITLE
Make a real documentation

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/NeuralNetDiffEq.jl#85]
Now that DiffEqFlux, ModelingToolkit, Surrogates, etc. all have one, NeuralNetDiffEq needs to get one.

Remaining documentation changes:

- [ ] Split the tutorials into separate ones on the sidebar. Have "copy-pastable code" on top, explained code below.
- [ ] Tutorials for the neural network ODE solver by using the tests
- [ ] More explanation in the deep BSDE methods as to where they come from and what they solve
- [ ] Separate out reference documentation
- [ ] For the reference documentation, convert some of the stuff from the README into docstrings, and use the docstrings in the documentation

https://github.com/SciML/NeuralNetDiffEq.jl/pull/86 for more details. I think that's what's needed to get it released, and then we can keep going from there!

**Comment by TeAmP0is0N** [comment]
@ChrisRackauckas I would like to work on it. Thank you!

**Comment by zzj0402** [comment]
What's the progress on documentation? I am available for splitting some workload.

**Comment by ChrisRackauckas** [comment]
Look at DiffEqFlux for where we want to go: https://diffeqflux.sciml.ai/dev/. That said, the current state is... https://github.com/SciML/NeuralNetDiffEq.jl/tree/master/docs . There hasn't been much progress made but we just need someone to just get started on it. The first thing to do would be to get docstrings setup and tutorials written.

**Comment by zzj0402** [comment]
Where is the neuralnetdiffeq.sciml.ai ? Documentation on SciML directs to github. I am looking at diffeqflux for the documentation structure.

**Comment by ChrisRackauckas** [comment]
>Where is the neuralnetdiffeq.sciml.ai ? Documentation on SciML directs to github. I am looking at diffeqflux for the documentation structure.

I need to set that up in the DNS. I'll have it done by tonight.

**Comment by ChrisRackauckas** [comment]
The DNS is enabled, but I forgot we hadn't setup deployment here yet. @kanav99 that's all you.

**Comment by ChrisRackauckas** [comment]
I think the major push is done here, so let's now start to handle the details.

**Comment by ChrisRackauckas** [comment]
Thanks @zzj0402 !
